# Independent settings for the local costmap
local_costmap:
  plugins:
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_sonar_layer
      type: 'range_sensor_layer::RangeSensorLayer'
    - name: obstacle_rgbd_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
    - name: social_layer_proxemic
      type: 'social_navigation_layers::ProxemicLayer'
    - name: social_layer_passing
      type: 'social_navigation_layers::PassingLayer'
